Task sa investigation child routers
nhsconnect/national-document-repository pull request #365
Opened 2024-05-15 21:59 UTC by SRAlexander

2024-05-16 15:29 UTC, RioKnightleyNHS requested changes

2024-05-16 15:29 UTC, RioKnightleyNHS commented on app/src/types/blocks/lloydGeorgeActions.ts
type ActionRoute = routeChildren && routes

2024-05-16 15:29 UTC, RioKnightleyNHS commented on app/src/components/blocks/_lloydGeorge/lloydGeorgeDownloadAllStage/LloydGeorgeDownloadAllStage.tsx
> +    return (
const Index = () => (<div> ... </div>)

2024-05-16 15:29 UTC, RioKnightleyNHS commented on app/src/components/blocks/_lloydGeorge/lloydGeorgeDownloadAllStage/LloydGeorgeDownloadAllStage.tsx
> +                        <div
```element={<Index/>}```

2024-05-16 15:29 UTC, RioKnightleyNHS commented on app/src/pages/documentSearchResultsPage/DocumentSearchResultsPage.tsx
> +                                <h1 id="download-page-title">{pageHeader}</h1>
Same as above with an Index component

2024-05-16 15:29 UTC, RioKnightleyNHS commented on app/src/pages/lloydGeorgeUploadPage/LloydGeorgeUploadPage.tsx
> +                // const documentReference = "test123"
remove comment

2024-05-17 21:31 UTC, SRAlexander commented on app/src/types/blocks/lloydGeorgeActions.ts
Modified

2024-05-17 21:31 UTC, SRAlexander commented on app/src/components/blocks/_lloydGeorge/lloydGeorgeDownloadAllStage/LloydGeorgeDownloadAllStage.tsx
> +    return (
Modified

2024-05-17 21:31 UTC, SRAlexander commented on app/src/components/blocks/_lloydGeorge/lloydGeorgeDownloadAllStage/LloydGeorgeDownloadAllStage.tsx
> +                        <div
Modified

2024-05-17 21:31 UTC, SRAlexander commented on app/src/pages/lloydGeorgeUploadPage/LloydGeorgeUploadPage.tsx
> +                // const documentReference = "test123"
Done

2024-05-22 11:15 UTC, SRAlexander commented on app/src/pages/documentSearchResultsPage/DocumentSearchResultsPage.tsx
> +                                <h1 id="download-page-title">{pageHeader}</h1>
done

2024-05-24 13:12 UTC, joefong-nhs approved these changes

2024-05-24 13:17 UTC, merged