PRMP-1120 NRL Create pointer
nhsconnect/national-document-repository pull request #459
Opened 2024-11-04 17:25 UTC by NogaNHS

2024-11-06 15:26 UTC, steph-torres-nhs commented on lambdas/services/pds_api_service.py
> +class PdsApiService(PatientSearch, NhsOauthService):
Do we want to inherit, or compose/how do we want to handle auth?

2024-11-06 15:30 UTC, steph-torres-nhs commented on lambdas/services/nrl_api_service.py
> +            response.raise_for_status()
add log for success?

2024-11-06 15:36 UTC, steph-torres-nhs commented on lambdas/services/nrl_api_service.py
> +    def _get_end_user_ods_code(self):
"__" double underscore for private method

2024-11-06 15:44 UTC, steph-torres-nhs commented on lambdas/tests/unit/handlers/test_manage_nrl_pointer_handler.py
> +
test errors being thrown

2024-11-06 15:45 UTC, steph-torres-nhs commented on lambdas/tests/unit/handlers/test_manage_nrl_pointer_handler.py
> +def test_process_event_with_one_message(mock_service, context, set_env):
is there a way to test success?

2024-11-06 17:07 UTC, steph-torres-nhs commented on lambdas/services/base/nhs_oauth_service.py
> +        self.ssm_service = ssm_service()
callable?

2024-11-07 15:55 UTC, AndyFlintNHS requested changes

2024-11-07 15:55 UTC, AndyFlintNHS commented on lambdas/tests/unit/handlers/test_manage_nrl_pointer_handler.py
> +def test_process_event_with_few_message(mock_service, context, set_env):
I'd rename `few_messages` to `multiple_messages`

2024-11-07 15:55 UTC, AndyFlintNHS commented on lambdas/tests/unit/handlers/test_manage_nrl_pointer_handler.py
> +def test_process_event_with_few_message(mock_service, context, set_env):
I'd rename `few_message` to `multiple_messages`

2024-11-08 11:55 UTC, steph-torres-nhs approved these changes

2024-11-15 17:08 UTC, merged