[PRMP-1287] GetDocumentRef lambda
nhsconnect/national-document-repository pull request #489
Opened 2024-12-16 11:49 UTC by NogaNHS

2024-12-23 09:59 UTC, jack-nhs approved these changes

2024-12-24 14:05 UTC, jack-nhs approved these changes

2024-12-24 15:32 UTC, steph-torres-nhs commented on lambdas/models/fhir/R4/nrl_fhir_document_reference.py
>                      "attachment": self.attachment.model_dump(
reminder to self, these bits need bringing inline with changes made to the model in PRMP-1373 regarding mandatory fields etc

2025-01-03 09:54 UTC, mark-start-nhs commented
we can delete the 

lambdas/enums/fhir/__init__.py
lambdas/models/fhir/R4/__init__.py
lambdas/models/fhir/__init__.py

__init__ ' s

2025-01-06 16:11 UTC, mark-start-nhs commented on lambdas/tests/unit/handlers/test_nrl_get_document_reference_handler.py
> +
test coverage for

2025-01-08 09:36 UTC, mark-start-nhs approved these changes

2025-01-08 15:19 UTC, AndyFlintNHS requested changes

2025-01-08 16:17 UTC, AndyFlintNHS commented on lambdas/enums/lambda_error.py
> +        "fhir_coding": FhirIssueCoding.INVALID,
Had a conversation with Noga, this'd scope creep beyond this ticket, one to consider for the future.

2025-01-08 16:17 UTC, AndyFlintNHS commented on lambdas/handlers/nrl_get_document_reference_handler.py
> +            raise NRLGetDocumentReferenceException(
Had a conversation with Noga, this'd scope creep beyond this ticket, one to consider for the future.

2025-01-08 16:18 UTC, AndyFlintNHS approved these changes

2025-01-13 13:08 UTC, mark-start-nhs commented on lambdas/handlers/nrl_get_document_reference_handler.py
> +                404, LambdaError.DocumentReferenceNotFound
is 400 invalid request for required request values , additionally consider we can indicate the invalid parameter in the fhir diagnostic message   
invalid request: document_id ...

2025-01-13 13:56 UTC, steph-torres-nhs commented on lambdas/handlers/nrl_get_document_reference_handler.py
> +    path_params = event.get("pathParameters", {}).get("id", None)
i'm not sure I quite understand

2025-01-13 13:58 UTC, steph-torres-nhs commented on lambdas/handlers/nrl_get_document_reference_handler.py
> +        if not document_id or not bearer_token or not snomed_code:
validation only really applies to this lambda use case, so not too sure how helpful it would be?

2025-01-20 11:48 UTC, merged