[PRMP-1284] Add NRL pointer to creation to upload document journey
nhsconnect/national-document-repository pull request #497
Opened 2024-12-23 16:12 UTC by steph-torres-nhs

2025-01-03 14:10 UTC, steph-torres-nhs commented on lambdas/models/nrl_sqs_message.py
> +    # creation: str = ""
double check need for these attributes

2025-01-03 14:27 UTC, steph-torres-nhs commented on lambdas/services/upload_confirm_result_service.py
> +
add 'else' branch log, reason for not creating pointer, more than one document uploaded

2025-01-07 17:40 UTC, steph-torres-nhs commented on lambdas/models/fhir/R4/base_models.py
> +    system: Optional[str] = "http://hl7.org/fhir/issue-type"
sonarcloud mentions this is not https is there anything we can do about it?

2025-01-09 16:55 UTC, abid-nhs requested changes
Looks good. Just two minor changes requested

2025-01-13 12:20 UTC, abid-nhs approved these changes

2025-01-27 13:21 UTC, NogaNHS commented on lambdas/tests/unit/handlers/test_upload_confirm_result_handler.py
> +
Is this being used anywhere?

2025-01-27 16:57 UTC, merged